### PR TITLE
WIP: [gov]: Piloting sphinx alabaster theme

### PR DESCRIPTION
**Pull request by CsatariGergely**
This pr is only to figure out if the community likes the Sphinx Alabaster theme.
Part of the #3191 effort.

### CODE REVIEW

**Review by steelescotr — APPROVED** [review]
+1

**Comment by CsatariGergely** [comment]
It looks like this: 
image

I miss the in document navigation.

**Review by collivier — CHANGES_REQUESTED** [review]
very incomplete. That would lead to a disruptive navigation

**Comment by CsatariGergely** [comment]
> very incomplete. That would lead to a disruptive navigation

Yes I totally agree. My only problem is that Material seems to be the most mature theme. I plan to pilot some others also if time permits, but so far I'm not convinced that we should use anything else than Material.

**Review by gkunz — APPROVED** [review]
I'd like to see this getting merged for Nile

**Comment by CsatariGergely** [comment]
We decided to use the Picolo theme, so this needs to be closed.

**Pull request closed without merging**
