### PR TITLE
Repo lockdown

### PR DESCRIPTION
**Pull request by CsatariGergely**
Removal the content and disabling pull requests for RM, RA1, RI1, RC1, RA2, RI2 and RC2.

### CODE REVIEW

**Review by lylavoie — APPROVED** [review]
Looks good.

**Review by rgstori — APPROVED** [review]

**Review by lylavoie — APPROVED** [review]

**Review by bfcohen — APPROVED** [review]
OK

**Comment by CsatariGergely** [comment]
Removal of GitHub Actions was factored out to a separate pr (#3425)

**Comment by CsatariGergely** [comment]
Merged with bypassing the branch protection rules with the [approval of the TSC](https://wiki.anuket.io/display/HOME/2024-02-20+TSC+Agenda+and+Minutes).

**Pull request merged**
