### PR TITLE
NSM as federated network manager / Tungsten as CNI

### PR DESCRIPTION
**Pull request by wavell**
NSM as federated network manager / Tungsten as CNI

### CODE REVIEW

**Comment by CsatariGergely** [comment]
@wawell are you sure you wanted to create this pr against Moselle? We just finished the work on Nile and the work on Orinoco starts soon, so Mosselle is a kinda old release already.

**Comment by pgoyal01** [comment]
@CsatariGergely @rgstori Why is this authorized to be merged even without any reviews?

**Comment by rgstori** [comment]
it's because the target branch is `stable:moselle` instead of `develop`
the target should be changed, but I would also recommend to add a branch protection rule for the `stable` branches (which I can't do as I'm not an admin)

**Comment by rgstori** [comment]
I've now changed the target to `master`, but that has automatically brought over all the changes from moselle to nile - maybe worth to re-do this in a new PR based off `nile`?

**Comment by CsatariGergely** [comment]
@wavell can you please create this pr against the master?

**Comment by CsatariGergely** [comment]
> it's because the target branch is `stable/moselle` instead of `develop` the target should be changed, but I would also recommend to add a branch protection rule for the `stable` branches (which I can't do as I'm not an admin)

Maybe we should discuss this in the TSC or in a mail or here. According to @collivier having branch protection rules for the stable/* branches would kill our current cherry-picking practices. Off course I would be more happy with more rules and automation :)

**Pull request closed without merging**
